drop table if exists pda_details;
drop table if exists pda_sorts;
drop table if exists pda_tags;
drop table if exists pda_types;
drop table if exists pda_units;
drop table if exists hibernate_sequence;
create table pda_details (id integer not null auto_increment, code integer not null, count integer not null, description varchar(300) not null, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_sorts (id integer not null, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_tags (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_types (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_units (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table pda_details drop foreign key FK2oph8wmgrg6ql6gm4vv3v9wgj;
alter table pda_details drop foreign key FKr13pmd80220s8igg1a1txqjsa;
alter table pda_details drop foreign key FK18gvygy4bkbx8hso161c3tdsv;
alter table pda_details drop foreign key FK9ykimu6jsiwre2slg3doog8qw;
drop table if exists pda_details;
drop table if exists pda_sorts;
drop table if exists pda_tags;
drop table if exists pda_types;
drop table if exists pda_units;
drop table if exists hibernate_sequence;
create table pda_details (id integer not null auto_increment, code integer not null, count integer not null, description varchar(300) not null, name varchar(50) not null, sortId integer not null, tagId integer not null, typeId integer not null, unitId integer not null, primary key (id)) engine=InnoDB;
create table pda_sorts (id integer not null, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_tags (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_types (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_units (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table pda_details add constraint FK2oph8wmgrg6ql6gm4vv3v9wgj foreign key (sortId) references pda_sorts (id);
alter table pda_details add constraint FKr13pmd80220s8igg1a1txqjsa foreign key (tagId) references pda_tags (id);
alter table pda_details add constraint FK18gvygy4bkbx8hso161c3tdsv foreign key (typeId) references pda_types (id);
alter table pda_details add constraint FK9ykimu6jsiwre2slg3doog8qw foreign key (unitId) references pda_units (id);
alter table pda_details drop foreign key FK2oph8wmgrg6ql6gm4vv3v9wgj;
alter table pda_details drop foreign key FKr13pmd80220s8igg1a1txqjsa;
alter table pda_details drop foreign key FK18gvygy4bkbx8hso161c3tdsv;
alter table pda_details drop foreign key FK9ykimu6jsiwre2slg3doog8qw;
drop table if exists pda_details;
drop table if exists pda_sorts;
drop table if exists pda_tags;
drop table if exists pda_types;
drop table if exists pda_units;
drop table if exists hibernate_sequence;
create table pda_details (id integer not null auto_increment, code integer not null, count integer not null, description varchar(300) not null, name varchar(50) not null, sortId integer not null, tagId integer not null, typeId integer not null, unitId integer not null, primary key (id)) engine=InnoDB;
create table pda_sorts (id integer not null, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_tags (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_types (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_units (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table pda_details add constraint FK2oph8wmgrg6ql6gm4vv3v9wgj foreign key (sortId) references pda_sorts (id);
alter table pda_details add constraint FKr13pmd80220s8igg1a1txqjsa foreign key (tagId) references pda_tags (id);
alter table pda_details add constraint FK18gvygy4bkbx8hso161c3tdsv foreign key (typeId) references pda_types (id);
alter table pda_details add constraint FK9ykimu6jsiwre2slg3doog8qw foreign key (unitId) references pda_units (id);
alter table pda_details drop foreign key FK2oph8wmgrg6ql6gm4vv3v9wgj;
alter table pda_details drop foreign key FKr13pmd80220s8igg1a1txqjsa;
alter table pda_details drop foreign key FK18gvygy4bkbx8hso161c3tdsv;
alter table pda_details drop foreign key FK9ykimu6jsiwre2slg3doog8qw;
drop table if exists pda_details;
drop table if exists pda_sorts;
drop table if exists pda_tags;
drop table if exists pda_types;
drop table if exists pda_units;
drop table if exists hibernate_sequence;
create table pda_details (id integer not null auto_increment, code integer not null, count integer not null, description varchar(300) not null, name varchar(50) not null, sortId integer not null, tagId integer not null, typeId integer not null, unitId integer not null, primary key (id)) engine=InnoDB;
create table pda_sorts (id integer not null, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_tags (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_types (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_units (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table pda_details add constraint FK2oph8wmgrg6ql6gm4vv3v9wgj foreign key (sortId) references pda_sorts (id);
alter table pda_details add constraint FKr13pmd80220s8igg1a1txqjsa foreign key (tagId) references pda_tags (id);
alter table pda_details add constraint FK18gvygy4bkbx8hso161c3tdsv foreign key (typeId) references pda_types (id);
alter table pda_details add constraint FK9ykimu6jsiwre2slg3doog8qw foreign key (unitId) references pda_units (id);
alter table pda_details drop foreign key FK2oph8wmgrg6ql6gm4vv3v9wgj;
alter table pda_details drop foreign key FKr13pmd80220s8igg1a1txqjsa;
alter table pda_details drop foreign key FK18gvygy4bkbx8hso161c3tdsv;
alter table pda_details drop foreign key FK9ykimu6jsiwre2slg3doog8qw;
drop table if exists pda_details;
drop table if exists pda_sorts;
drop table if exists pda_tags;
drop table if exists pda_types;
drop table if exists pda_units;
drop table if exists hibernate_sequence;
create table pda_details (id integer not null auto_increment, code integer not null, count integer not null, description varchar(300) not null, name varchar(50) not null, sortId integer not null, tagId integer not null, typeId integer not null, unitId integer not null, primary key (id)) engine=InnoDB;
create table pda_sorts (id integer not null, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_tags (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_types (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_units (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table pda_details add constraint FK2oph8wmgrg6ql6gm4vv3v9wgj foreign key (sortId) references pda_sorts (id);
alter table pda_details add constraint FKr13pmd80220s8igg1a1txqjsa foreign key (tagId) references pda_tags (id);
alter table pda_details add constraint FK18gvygy4bkbx8hso161c3tdsv foreign key (typeId) references pda_types (id);
alter table pda_details add constraint FK9ykimu6jsiwre2slg3doog8qw foreign key (unitId) references pda_units (id);
alter table pda_details drop foreign key FK2oph8wmgrg6ql6gm4vv3v9wgj;
alter table pda_details drop foreign key FKr13pmd80220s8igg1a1txqjsa;
alter table pda_details drop foreign key FK18gvygy4bkbx8hso161c3tdsv;
alter table pda_details drop foreign key FK9ykimu6jsiwre2slg3doog8qw;
drop table if exists pda_details;
drop table if exists pda_sorts;
drop table if exists pda_tags;
drop table if exists pda_types;
drop table if exists pda_units;
drop table if exists hibernate_sequence;
create table pda_details (id integer not null auto_increment, code integer not null, count integer not null, description varchar(300) not null, name varchar(50) not null, sortId integer not null, tagId integer not null, typeId integer not null, unitId integer not null, primary key (id)) engine=InnoDB;
create table pda_sorts (id integer not null, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_tags (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_types (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table pda_units (id integer not null auto_increment, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table pda_details add constraint FK2oph8wmgrg6ql6gm4vv3v9wgj foreign key (sortId) references pda_sorts (id);
alter table pda_details add constraint FKr13pmd80220s8igg1a1txqjsa foreign key (tagId) references pda_tags (id);
alter table pda_details add constraint FK18gvygy4bkbx8hso161c3tdsv foreign key (typeId) references pda_types (id);
alter table pda_details add constraint FK9ykimu6jsiwre2slg3doog8qw foreign key (unitId) references pda_units (id);
